//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChittieAPI
{
    using System;
    using System.Collections.Generic;

    public partial class ChitTermGroup
    {
        public int sno { get; set; }
        public string chitid { get; set; }
        public Nullable<int> termnumber { get; set; }
        public string termgroupid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> EMIAmount { get; set; }

    }
    public class CurrentTenureBidStatus
    {
        public int BidAmount { get; set; }
        public bool BidTaken { get; set; }
        public string BidTakenByUser{ get; set; }
        public string BidTakenByUserId { get; set; }
        public int BidTakenAmount { get; set; }

    }

}
