//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChittieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitInvitation
    {
        public int SNO { get; set; }
        public string Organiseruserid { get; set; }
        public string inviteuserid { get; set; }
        public string chitid { get; set; }
        public string invitationid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<int> invitationstatus { get; set; }
    }
}
