//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChittieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitConnection
    {
        public int sno { get; set; }
        public string chitid { get; set; }
        public string connectionid { get; set; }
        public string userid { get; set; }
        public Nullable<bool> organiser { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
