//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChittieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitBidTransaction
    {
        public int sno { get; set; }
        public string userid { get; set; }
        public string chitid { get; set; }
        public string termgroupid { get; set; }
        public Nullable<int> amount { get; set; }
        public string bidID { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> BidStatus { get; set; }
    }
}
