//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChittieAPI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ChitDetail
    {
        public int sno { get; set; }
        public string chitname { get; set; }
        public int tenure { get; set; }
        public decimal percentage { get; set; }
        public Nullable<int> membercount { get; set; }
        public System.DateTime startdate { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<int> status { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string chitid { get; set; }
        public Nullable<int> emi { get; set; }
    }
}
