//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChittieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class smswarehouse
    {
        public int smswarid { get; set; }
        public string userid { get; set; }
        public string messageaddress { get; set; }
        public string messagebody { get; set; }
        public Nullable<System.DateTime> messagetime { get; set; }
        public Nullable<int> messageid { get; set; }
        public string servicecenterid { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    }
}
