//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChittieAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubsrciptionTest
    {
        public int sno { get; set; }
        public string phonenumber { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> messagedate { get; set; }
    }
}
